### ISSUE TITLE
It removes entire line whn trying to run unexisting snippet.

### ISSUE THREAD

**Issue by RB-Lab** [jrowny/brackets-snippets#30] opened 2013-12-13 20:58 UTC
I'm trying do the following:

1) created snippet triggered with `fu` to insert anonymous function;
2) type `socket.on('textMsg', fu`
3) trying to run snippet 

_Expected behaviour:_ snippet inserted or at least noting
_Actual behaviour:_ line  `socket.on('textMsg', fu` removed

_Additional info:_ snippet runs ok on a new line with only `fu`. BTW, is it possible to run snippet if its trigger doesn't occupy whole line?

**Comment by jrowny** [comment] 2014-03-10 18:17
Closed as duplicate of issue #15

**Closed as completed by jrowny** 2014-03-10 18:17 UTC

**Comment by RB-Lab** [comment] 2014-03-10 20:06
isn't #15 about only part of this issue? I mean if you mistaken in your snippet or forgot argument it will remove whole line when you hit shortcut. That's confusing behaviour...

**Comment by jrowny** [comment] 2014-03-10 20:10
Nothing should happen if a valid trigger is not found. If something does happen, I believe we need an issue isolated to just that problem.

**Comment by zaggino** [comment] 2014-03-10 23:15
@RB-Lab This behaviour is also fixed in https://github.com/jrowny/brackets-snippets/pull/35
