### ISSUE TITLE
snippets folder

### ISSUE THREAD

**Issue by benoitwimart** [jrowny/brackets-snippets#22] opened 2013-09-14 13:45 UTC
Hi,

After add my own ".snippet" file, Mac OS X add a ".DS_Store" file and brackets-snippets doesn't start.
I used this command to remove this hidden file and fix it :
cd Users/…/Library/Application\ Support/Brackets/extensions/user/jrowny.brackets.snippets/data/snippets

sudo rm ".DS_Store"

B.

**Comment by jrowny** [comment] 2013-10-31 19:59
I'm closing this because it's a duplicate of issue #11. Please track #11 for progress on fixing this.

**Closed as completed by jrowny** 2013-10-31 19:59 UTC
